### ISSUE TITLE
Standalone install without docker

### ISSUE THREAD

**Issue by reinethernal** [zzzbatmand/openvpn-web-ui#1]
Hi!
Is there any way to install and run in without docker?

**Comment by SirWintour** [comment]
I would think so, but I will recommend you check out:
https://github.com/adamwalach/openvpn-web-ui
for more information, as this project is a merge of some of the forks on there.
I was trying to fix some of the problems, but haven't yet leaned how to program in GO, so I have somewhat left this project, and might make my own version in JS instead.

**Comment by reinethernal** [comment]
ok, thx)
